- name: setup-reproducer
  hosts: reproducer
  remote_user: "{{ login_username }}"
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - user:
        name: rebuilder 
        comment: "Unprivileged account to rebuild packages"
        uid: 1001

    - name: Install pbuilder
      apt:
        name: pbuilder
        state: latest
