- name: setup-builder
  hosts: builders
  remote_user: "{{ login_username }}"
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: Install sbuild
      apt:
        name: sbuild
        state: latest

    - name: Install perl datetime
      apt:
        name: libdatetime-format-strptime-perl
        state: latest

    - name: Install perl web abilities
      apt:
        name: libwww-perl
        state: latest

    - name: Install perl json
      apt:
        name: libjson-perl
        state: latest
