- name: setup-builder
  hosts: builders
  remote_user: "{{ login_username }}"
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: Install sbuild
      apt:
        name: sbuild
        state: latest

    - name: Install perl datetime
      apt:
        name: libdatetime-format-strptime-perl
        state: latest

    - name: Install perl web abilities
      apt:
        name: libwww-perl
        state: latest

    - name: Install perl json
      apt:
        name: libjson-perl
        state: latest

    - name: Set up base sbuild chroot
      command: sbuild-createchroot --include=eatmydata,ccache,gnupg --make-sbuild-tarball=/src/chroot/sid-amd64-sbuild.tar.gz sid `mktemp -d` http://deb.debian.org/debian
      args:
        creates: /srv/chroot/sid-amd64-sbuild.tar.gz
